version: '3.8'

services:
  adr-it:
    build: .
    volumes:
      - .:/app
    environment:
      - GOOGLE_API_KEY=${GOOGLE_API_KEY}
      - GOOGLE_CX=${GOOGLE_CX}
    command: [ "resolve", "-i", "batch_results_LO.csv", "-o", "output_docker.csv" ]
